"""Bake logo outlines into a small cloud density atlas. Needs Pillow, no runtime dependency.

Sources are the real logos served by each company's Fluid storefront, checked
2026-09-07. Run from any directory; generated bytes are committed with the client.
Only the alpha/ink silhouette is used. Source colors do not become cloud colors.
"""
import base64
import io
import math
from pathlib import Path
import urllib.request

from PIL import Image

SIZE = 128
SOURCES = [
    ("wellnah", "https://ik.imagekit.io/fluid/980243165/Wellnah_logo-secondary_iYFIri9xDs.png", "alpha"),
    ("nuvamed", "https://ik.imagekit.io/fluid/980243164/Favicon_ukPXsytUQ6.png", "ink"),
    ("oliabo", "https://ik.imagekit.io/fluid/980243071/images/7G4WCY/oliabo-logo_162eV0E-M.png", "alpha"),
]


def bake(url, mode, company):
    with urllib.request.urlopen(url, timeout=20) as response:
        source = Image.open(io.BytesIO(response.read())).convert("RGBA")
    if mode == "ink":
        mask = Image.new("L", source.size)
        mask.putdata([round(a * (1 - min(r, g, b) / 255)) for r, g, b, a in source.get_flattened_data()])
    else:
        mask = source.getchannel("A")
    mask = mask.point(lambda p: 255 if p > 110 else 0)
    mask = mask.crop(mask.getbbox())
    mask.thumbnail((104, 67), Image.Resampling.LANCZOS)
    tile = Image.new("L", (SIZE, SIZE))
    tile.paste(mask, ((SIZE - mask.width) // 2, (SIZE - mask.height) // 2))
    inside = [p > 110 for p in tile.get_flattened_data()]
    edges = []
    for y in range(1, SIZE - 1):
        for x in range(1, SIZE - 1):
            i = y * SIZE + x
            if any(inside[i] != inside[j] for j in (i - 1, i + 1, i - SIZE, i + SIZE)):
                edges.append((x, y))
    values = bytearray()
    # Bottom-up bytes match the shader's +Y coordinates. Signed distance is
    # encoded with a .5 unit range on either side of the outline (128 = edge).
    for y in reversed(range(SIZE)):
        for x in range(SIZE):
            distance = math.sqrt(min((x - ex) ** 2 + (y - ey) ** 2 for ex, ey in edges)) + .5
            signed = distance * (-1 if inside[y * SIZE + x] else 1) * 3.4 / SIZE
            values.append(round(max(0, min(255, 127.5 + signed * 255))))
    return values


tiles = [bake(url, mode, company) for company, url, mode in SOURCES]
atlas = bytearray()
for y in range(SIZE):
    for tile in tiles:
        atlas.extend(tile[y * SIZE:(y + 1) * SIZE])
encoded = base64.b64encode(atlas).decode()
output = Path(__file__).resolve().parents[1] / "client/prototypes/factory25dCloudCompanyMasks.ts"
output.write_text(
    "// Generated by scripts/build-cloud-company-masks.py; do not hand-edit.\n"
    "// 128px tiles: Wellnah symbol, NuvaMed N+, Oliabo wordmark.\n"
    f"export const CLOUD_COMPANY_MASK_SIZE = {SIZE};\n"
    f"const encoded = '{encoded}';\n"
    "export function cloudCompanyMaskBytes() {\n"
    "  return Uint8Array.from(atob(encoded), char => char.charCodeAt(0));\n"
    "}\n"
)
print(f"Baked {len(tiles)} logo masks: {len(atlas)} bytes, no runtime image requests.")
